-- Lua Demo — Shows what the Fengari Lua VM can do inside RepoWeb
-- This script demonstrates all available DOM manipulation APIs

repoweb:log("[Lua Demo] Starting Lua engine demonstration...")

-- 1. Get element and change its content
local title = repoweb:getElementById("lua-title")
if title then
  repoweb:setTextContent(title, "Lua VM Active!")
  repoweb:setStyle(title, "color", "#10b981")
end

-- 2. Create new DOM elements dynamically
local container = repoweb:getElementById("lua-demo-area")
if container then
  -- Create a card
  local card = repoweb:createElement("div")
  repoweb:setStyle(card, "background", "#1a1a1f")
  repoweb:setStyle(card, "border", "1px solid #2a2a30")
  repoweb:setStyle(card, "border-radius", "10px")
  repoweb:setStyle(card, "padding", "1.5rem")
  repoweb:setStyle(card, "margin-bottom", "1rem")

  local heading = repoweb:createElement("h3")
  repoweb:setTextContent(heading, "Generated by Lua")
  repoweb:setStyle(heading, "margin-bottom", "0.5rem")

  local desc = repoweb:createElement("p")
  repoweb:setTextContent(desc, "This entire card was created by logic.lua using the repoweb DOM API. No HTML was written for it.")
  repoweb:setStyle(desc, "color", "#8a8a95")
  repoweb:setStyle(desc, "font-size", "0.9rem")

  local counter = repoweb:createElement("p")
  repoweb:setStyle(counter, "margin-top", "1rem")
  repoweb:setStyle(counter, "font-size", "2rem")
  repoweb:setStyle(counter, "font-weight", "bold")
  repoweb:setStyle(counter, "color", "#10b981")
  repoweb:setTextContent(counter, "API calls made: 7")

  repoweb:appendChild(card, heading)
  repoweb:appendChild(card, desc)
  repoweb:appendChild(card, counter)
  repoweb:appendChild(container, card)
end

repoweb:log("[Lua Demo] DOM manipulation complete")
